# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np

In [ ]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [55]:
arr = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, skiprows=1, delimiter=',')
arr[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [56]:
arr[:, 1:].min(axis=0)

array([0, 1], dtype=int32)

In [57]:
arr[:, 1:].max(axis=0)

array([2147483647,         39], dtype=int32)

In [58]:
np.median(arr[:, 1:], axis=0)

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [59]:
arr[arr[:, 1] < np.percentile(arr[:, 1], 0.75, axis=0)]

array([[352940,      1,      3],
       [ 47249,      1,      8],
       [  9325,      0,     10],
       ...,
       [155921,      1,      2],
       [  2778,      0,     11],
       [  4747,      0,      9]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [60]:
arr[arr[:, 1] == 0].shape[0]

479

In [61]:
arr[arr[:, 1] == 0] = 1

In [62]:
arr[arr[:, 1] == 0].shape[0]

0

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [63]:
np.unique(arr[:, 0]).shape[0]

99522

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [64]:
a = np.unique(arr[:, 2])
a, a.shape[0]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39], dtype=int32), 37)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [65]:
arr[arr[:, 2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [66]:
(arr[:, 2] / arr[:, 1]).max()

23.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [67]:
arr[arr[:, 1] == np.sort(arr[:, 1])[::-1]][:100, 2].mean()

10.8

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [68]:
arr[np.random.randint(0, arr.shape[0], size=(10,))]

array([[375297,     15,      8],
       [186219,     15,      7],
       [ 95288,     45,      9],
       [130323,     20,      9],
       [116375,     80,      8],
       [426851,      5,      3],
       [334996,     60,      5],
       [146869,      1,      3],
       [476010,      5,     11],
       [501588,     23,      8]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [69]:
(arr[arr[:, 2] < arr[:, 2].mean()].shape[0] / arr.shape[0]) * 100

58.989000000000004

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [70]:
arr = np.c_[arr, ((arr[:, 1] < 20) * (arr[:, 2] < 5)).astype(np.int32)]

13. Выведите процент "простых" рецептов в датасете

In [71]:
arr[arr[:, 3] == 1].shape[0] / arr.shape[0] * 100

5.523

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [82]:
s = arr[arr[:, 1] < 10]
m = arr[(10 < arr[:, 1]) & (arr[:, 1] < 20)]
l = arr[20 <= arr[:, 1]]
d = min(s.shape[0], m.shape[0], l.shape[0])

np.stack([s[:d], m[:d], l[:d]]).shape

(3, 7588, 4)